let dpd_deconstructor = {
    "aniyatuddeso": "aniyatā + uddeso<br>aniyata + uddeso<br>aniyato + uddeso<br>aniyato + udda + eso<br>aniyata + udda + eso",
  "appaharitepi": "appaharite + api<br>appa + harite + api<br>api + aharite + api",
  "appitañca": "appitaṃ + ca",
  "asantepi": "asante + api<br>na + sante + api<br>asi + ante + api",
  "bhikkhunovādavaggo": "bhikkhunī + ovādavaggo<br>bhikkhuno + vāda + vaggo<br>bhikkhunī + ovāda + vaggo",
  "bhikkhupātimokkha": "bhikkhu + pātimokkha<br>bhikkhu + pāti + mokkha<br>bhikkhu + pātiṃ + okkha",
  "bhikkhupātimokkhaṃ": "bhikkhu + pātimokkhaṃ<br>bhikkhu + pāti + mokkhaṃ<br>bhikkhu + pātiṃ + okkhaṃ",
  "bhikkhūpi": "bhikkhū + api",
  "bhuñjissāmīti": "bhuñjissāmi + iti<br>bhuñji + assāmi + iti<br>bhuñji + sāmi + iti",
  "byāharissāmīti": "byāharissāmi + iti<br>byāhara + issāmi + iti",
  "cassa": "ce + assa<br>ca + assa",
  "ceva": "ca + eva<br>ce + eva",
  "chandañca": "chandaṃ + ca<br>cha + indaṃ + ca",
  "chaḍḍessāmīti": "chaḍḍessāmi + iti<br>chaḍḍe + sāmī + iti<br>chaḍḍe + sāmi + iti",
  "cīvarañca": "cīvaraṃ + ca",
  "desessāmīti": "desessāmi + iti<br>desi + essāmi + iti<br>deso + essāmi + iti",
  "dhārayāmīti": "dhārayāmi + iti<br>dhāra + yāmi + iti<br>dhāra + ayāmi + iti",
  "ekassapi": "ekassa + api<br>eka + ssu + api<br>eka + assu + api",
  "evamassa": "evaṃ + assa",
  "gamissāmīti": "gamissāmi + iti<br>gami + assāmi + iti<br>gama + issāmi + iti",
  "gāmantarampi": "gāmantaraṃ + api<br>gāmantara + api<br>gāmaṃ + taraṃ + api<br>gāmi + antaraṃ + api",
  "hissa": "hi + assa<br>hi + ssa",
  "iccetaṃ": "iti + etaṃ",
  "itissa": "iti + assa",
  "kaccittha": "kacci + attha<br>kacci + ettha",
  "karissāmīti": "karissāmi + iti<br>kara + issāmi + iti<br>kari + assāmi + iti",
  "neva": "na + eva",
  "nisīdissāmīti": "nisīdissāmi + iti<br>nisīdi + assāmi + iti<br>nisīda + issāmi + iti",
  "nivāsessāmīti": "nivāsessāmi + iti<br>nivāsa + essāmi + iti<br>nivāsa + issāmi + iti",
  "olokessāmīti": "olokessāmi + iti<br>oloke + sāmi + iti<br>oloke + sāmī + iti",
  "pakkhipissāmīti": "pakkhipissāmi + iti<br>pakkhi + pissāmi + iti<br>pakkhipi + issāmi + iti",
  "pattakallanti": "pattakallaṃ + iti<br>patta + kallaṃ + iti<br>pattā + akallaṃ + iti",
  "paṭiggahessāmīti": "paṭiggahessāmi + iti<br>paṭiggahe + issāmi + iti<br>paṭiggahā + essāmi + iti",
  "piṇḍapātamattampi": "piṇḍapātamattaṃ + api<br>piṇḍapātamatta + api<br>piṇḍapātaṃ + attaṃ + api<br>piṇḍapāta + mattaṃ + api",
  "pubbakaraṇanti": "pubbakaraṇaṃ + iti<br>pubba + karaṇaṃ + iti<br>pubbaka + raṇaṃ + iti",
  "pubbakaraṇapubbakiccāni": "pubbakaraṇa + pubbakiccāni<br>pubbakaraṇa + pubba + kiccāni<br>pubbaka + raṇa + pubbakiccāni",
  "pubbakiccanti": "pubbakiccaṃ + iti<br>pubba + kiccaṃ + iti<br>pubba + akiccaṃ + iti",
  "pārupissāmīti": "pārupissāmi + iti<br>pārupa + issāmi + iti<br>pāra + upissāmi + iti",
  "pārājikuddeso": "pārājika + uddeso<br>pāra + ajika + uddeso<br>pārājika + udda + eso",
  "ruciñca": "ruciṃ + ca",
  "samaṇuddesopi": "samaṇuddeso + api<br>samaṇa + uddeso + api",
  "sammatopi": "sammato + api<br>sa + mato + api",
  "satiyāpi": "satiyā + api<br>satiyaṃ + api<br>sati + ayaṃ + api",
  "saṅghādisesuddeso": "saṅghādisesa + uddeso<br>saṅghā + disesu + uddeso<br>saṅgha + ādisesu + uddeso",
  "sikkhitabbanti": "sikkhitar + vanti<br>sikkhitabbaṃ + iti<br>sikkhi + tad + vanti",
  "suddhapācittiyā": "suddha + pācittiyā<br>suddhā + api + acittiyā<br>suddhi + api + acittiyā",
  "sugatacīvarappamāṇanti": "sugatacīvarappamāṇaṃ + iti<br>sugatacīvara + pamāṇaṃ + iti<br>sugatacīvara + appamāṇaṃ + iti",
  "suppavāyitañca": "suppavāyitaṃ + ca<br>su + pavāyitaṃ + ca<br>suppa + vāyitaṃ + ca",
  "suvilekhitañca": "suvilekhitaṃ + ca<br>su + vilekhitaṃ + ca",
  "suvitacchitañca": "suvitacchitaṃ + ca<br>su + vitacchitaṃ + ca",
  "suvītañca": "suvītaṃ + ca<br>su + vītaṃ + ca",
  "tasseva": "tassa + eva",
  "tatheva": "tatha + eva<br>tathā + eva",
  "tañca": "taṃ + ca",
  "taṅkhaṇikāyapi": "taṅkhaṇikāyo + api<br>taṅkhaṇikāyaṃ + api<br>taṅkhaṇikā + api<br>taṅkhaṇikāya + api<br>taṅkhaṇikā + yo + api",
  "thenosīti": "theno + asi + iti",
  "tiracchānagatāyapi": "tiracchānagatāyo + api<br>tiracchānagatāyaṃ + api<br>tiracchānagatā + api<br>tiracchānagatāya + api<br>tiracchānagatā + yo + api",
  "upādāyāti": "upādāya + iti",
  "vitthatañca": "vitthataṃ + ca<br>vittha + taṃ + ca",
  "vivarissāmīti": "vivarissāmi + iti<br>vivari + assāmi + iti<br>vivari + issāmi + iti",
  "vāssa": "vā + assa",
  "yassa": "yo + assa",
  "āyatañca": "āyataṃ + ca"
}